apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: observability
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b

iam:
  serviceRoleARN: arn:aws:iam::975050354644:role/eksClusterRole

nodeGroups:
  - name: observability-ng-private
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    privateNetworking: true  # Equivalent to --node-private-networking
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        appMesh: true
        albIngress: true
    asgMetricsCollection:
      - granularity: 1Minute
